### ISSUE TITLE
view_listing doesn't work

### ISSUE THREAD

**Issue by baraklevyy** [evandiewald/rto-token#2]
When I'm trying to startup the Demo, I'm trying to reach 'View Listing" and I got this error:

![image](https://user-images.githubusercontent.com/62298910/130786591-e3ed8e39-c107-4f28-a9b9-5de026b0f3c7.png)
 and more detailed:

![image](https://user-images.githubusercontent.com/62298910/130786643-848845ca-f577-4c79-9f07-d7136e2feddc.png)

How can I fix that?

**Comment by evandiewald** [comment]
This error means that the table has not been created yet. I've pushed a new commit (e427e2c3) that adds a quick check to see if the 'listings' table already exists, and if not, it will be created for you. Here is that simple check, which is now after the table is defined in `main.py`: 

```
# create table if it does not already exist
if not inspect(db).has_table('listings'):
    print('\'listings\' table does not yet exist. Creating it now...')
    table.create()```
