### ISSUE TITLE
sign_transaction

### ISSUE THREAD

**Issue by baraklevyy** [evandiewald/rto-token#4]
Since you didn;t use the function : 
![image](https://user-images.githubusercontent.com/62298910/131225539-724d4d47-c222-44db-bdd8-778803d352b5.png)
 Can you please elaborate what's the use of that function and how to use it?
 
 Another issue is, if I'm adding property from non-Admin, the property is still visible in the 'view listings'.
So can you add any solution to that? maybe using the mention function?

**Comment by evandiewald** [comment]
This is a function to sign the transaction using your private key directly, rather than using MetaMask. This is considered a significant security risk, but was used during testing of the app.
